/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai76;

import javax.swing.ImageIcon;

/**
 *
 * @author bachp
 */
public class baitap76 extends javax.swing.JFrame {

    /**
     * Creates new form baitap76
     */
    public baitap76() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxChoosePic = new javax.swing.JComboBox<>();
        jLabelPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxChoosePic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one watch ", "Watch 1", "Watch 2", "Watch 3", "Watch 4" }));
        jComboBoxChoosePic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoosePicActionPerformed(evt);
            }
        });

        jLabelPic.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jComboBoxChoosePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabelPic, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jComboBoxChoosePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    Select one watch 
//Watch 1
//Watch 2
//Watch 3
//Watch 
    private void jComboBoxChoosePicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoosePicActionPerformed
        String srcPic = "src/image/";
        if(jComboBoxChoosePic.getSelectedItem() == "Select one watch "){
            jLabelPic.setIcon(null);
        }
        if(jComboBoxChoosePic.getSelectedItem() == "Watch 1"){
            ImageIcon imgIcon1 = new ImageIcon(srcPic+"1.jpg");
            jLabelPic.setIcon(imgIcon1);
        }
        if(jComboBoxChoosePic.getSelectedItem() == "Watch 2"){
            ImageIcon imgIcon2 = new ImageIcon(srcPic+"2.jpg");
            jLabelPic.setIcon(imgIcon2);
        }
        if(jComboBoxChoosePic.getSelectedItem() == "Watch 3"){
            ImageIcon imgIcon3 = new ImageIcon(srcPic+"3.jpg");
            jLabelPic.setIcon(imgIcon3);
        }
        if(jComboBoxChoosePic.getSelectedItem() == "Watch 4"){
            ImageIcon imgIcon4 = new ImageIcon(srcPic+"4.jpg");
            jLabelPic.setIcon(imgIcon4);
        }
    }//GEN-LAST:event_jComboBoxChoosePicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baitap76.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baitap76.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baitap76.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baitap76.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baitap76().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxChoosePic;
    private javax.swing.JLabel jLabelPic;
    // End of variables declaration//GEN-END:variables
}
