/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai79;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author bachp
 */

public class Bai79 extends javax.swing.JFrame {
    DefaultListModel dm = new DefaultListModel();
    
    /**
     * Creates new form Bai79
     */
    public Bai79() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBtnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnBoldSoChan = new javax.swing.JButton();
        jbtnBoldSole = new javax.swing.JButton();
        jbtnBoldSoNguyenTo = new javax.swing.JButton();
        jbtnUnBold = new javax.swing.JButton();
        jbtnBoldDelete = new javax.swing.JButton();
        jbtnSumList = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnInput = new javax.swing.JButton();
        jTxtInput = new javax.swing.JTextField();
        jCkbNhapSoAm = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNumber = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnClose.setText("Dong chuong trinh");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Thao tac tren JList - Checkbox");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chon tac vu"));

        jbtnBoldSoChan.setText("To den so chan");
        jbtnBoldSoChan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBoldSoChanActionPerformed(evt);
            }
        });

        jbtnBoldSole.setText("To den so le");
        jbtnBoldSole.setActionCommand("");
        jbtnBoldSole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBoldSoleActionPerformed(evt);
            }
        });

        jbtnBoldSoNguyenTo.setText("To den so nguyen to");
        jbtnBoldSoNguyenTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBoldSoNguyenToActionPerformed(evt);
            }
        });

        jbtnUnBold.setText("Bo t0 den");
        jbtnUnBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUnBoldActionPerformed(evt);
            }
        });

        jbtnBoldDelete.setText("Xoa các giá trị đang tô đen");
        jbtnBoldDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBoldDeleteActionPerformed(evt);
            }
        });

        jbtnSumList.setText("Tổng giá trị trong JList");
        jbtnSumList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSumListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSumList)
                    .addComponent(jbtnBoldSoChan)
                    .addComponent(jbtnBoldDelete)
                    .addComponent(jbtnUnBold)
                    .addComponent(jbtnBoldSole)
                    .addComponent(jbtnBoldSoNguyenTo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnBoldSoChan)
                .addGap(9, 9, 9)
                .addComponent(jbtnBoldSole, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnBoldSoNguyenTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnUnBold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnBoldDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSumList))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhap Thong Tin"));

        jbtnInput.setText("Nhap");
        jbtnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInputActionPerformed(evt);
            }
        });

        jCkbNhapSoAm.setText("Cho nhap so am");

        jScrollPane1.setViewportView(jListNumber);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCkbNhapSoAm)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnInput)
                    .addComponent(jTxtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCkbNhapSoAm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jBtnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jBtnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isNumeric(String strNum) {
        if (strNum == null) {
            return false;
        }
        try {
            Integer.parseInt(strNum);
            return true;
        }
        catch (NumberFormatException e) {
             return false;
        }
    }
    
    private void jbtnBoldSoChanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoldSoChanActionPerformed
        ArrayList<Integer> listIndex = new ArrayList<>();
        for(int i = 0; i < jListNumber.getModel().getSize(); i++){
            int numOnList = Integer.parseInt(jListNumber.getModel().getElementAt(i));
            if(numOnList % 2 == 0){
//                
                listIndex.add(i);
            }
        int[] listIndexInt = listIndex.stream().mapToInt(Integer::intValue).toArray();
        jListNumber.setSelectedIndices(listIndexInt);
        }                                              
    }//GEN-LAST:event_jbtnBoldSoChanActionPerformed

    private void jbtnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInputActionPerformed
        // TODO add your handling code here:
        jListNumber.setModel(dm);
        jListNumber.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if(isNumeric(jTxtInput.getText())){    
            if(jTxtInput.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Vui long khong bo trong");
            }
            
            if(!jCkbNhapSoAm.isSelected()){
                int numInput = Integer.parseInt(jTxtInput.getText());
                if(numInput < 0){
                    JOptionPane.showMessageDialog(this, "Vui long nhap so > 0");
                    return;
                }
            }
            if(jCkbNhapSoAm.isSelected()){
                dm.addElement(jTxtInput.getText());
            }
            else{
                dm.addElement(jTxtInput.getText());
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "vui long nhap so!");
        }
        
        jTxtInput.setText("");
    }//GEN-LAST:event_jbtnInputActionPerformed

    private void jbtnBoldSoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoldSoleActionPerformed
        // TODO add your handling code here:
        ArrayList<Integer> listIndex = new ArrayList<>();
        for(int i = 0; i < jListNumber.getModel().getSize(); i++){
            int numOnList = Integer.parseInt(jListNumber.getModel().getElementAt(i));
            if(numOnList % 2 != 0){
//                
                listIndex.add(i);
            }
            int[] listIndexInt = listIndex.stream().mapToInt(Integer::intValue).toArray();
            jListNumber.setSelectedIndices(listIndexInt);
        }
    }//GEN-LAST:event_jbtnBoldSoleActionPerformed

    //so nguyen to area
    
     public boolean checkPrimeNum(int n){
          if (n < 2) {
            return false;
        }
        // check so nguyen to khi n >= 2
        int squareRoot = (int) Math.sqrt(n);
        for (int i = 2; i <= squareRoot; i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
     }

    
    private void jbtnBoldSoNguyenToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoldSoNguyenToActionPerformed
        // TODO add your handling code here:
         ArrayList<Integer> listIndex = new ArrayList<>();
        for(int i = 0; i < jListNumber.getModel().getSize(); i++){
            int numOnList = Integer.parseInt(jListNumber.getModel().getElementAt(i));
            if(checkPrimeNum(numOnList)){
                listIndex.add(i);
            }
            int[] listIndexInt = listIndex.stream().mapToInt(Integer::intValue).toArray();
            jListNumber.setSelectedIndices(listIndexInt);
        }
    }//GEN-LAST:event_jbtnBoldSoNguyenToActionPerformed

    private void jbtnUnBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUnBoldActionPerformed
        jListNumber.clearSelection();
    }//GEN-LAST:event_jbtnUnBoldActionPerformed

    private void jbtnBoldDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBoldDeleteActionPerformed

        for(int i =0; i < jListNumber.getModel().getSize(); i++){
            int index = jListNumber.getSelectedIndex();
            if(index < 0){
                JOptionPane.showMessageDialog(this, "Khong co gia tri de xoa");
                return;
            }
            else{
                dm.removeElementAt(i);
            }
        }
    }//GEN-LAST:event_jbtnBoldDeleteActionPerformed

    private void jbtnSumListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSumListActionPerformed
        int sum =0;
        for(int i = 0; i < jListNumber.getModel().getSize(); i++){
            sum += Integer.parseInt(jListNumber.getModel().getElementAt(i));
        }
        JOptionPane.showMessageDialog(this, sum);
    }//GEN-LAST:event_jbtnSumListActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai79.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai79.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai79.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai79.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai79().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JCheckBox jCkbNhapSoAm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtInput;
    private javax.swing.JButton jbtnBoldDelete;
    private javax.swing.JButton jbtnBoldSoChan;
    private javax.swing.JButton jbtnBoldSoNguyenTo;
    private javax.swing.JButton jbtnBoldSole;
    private javax.swing.JButton jbtnInput;
    private javax.swing.JButton jbtnSumList;
    private javax.swing.JButton jbtnUnBold;
    // End of variables declaration//GEN-END:variables
}
